### ISSUE TITLE
Replace packr with native Go embed

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener-extension-os-suse-chost#54]
**How to categorize this issue?**

/area os
/kind enhancement
/priority 3
/os suse-chost

**What would you like to be added**:
Replace packr with native Go embed

**Why is this needed**:
Less external dependencies.

**Comment by vpnachev** [comment]
I think this was done some time ago with https://github.com/gardener/gardener-extension-os-suse-chost/pull/39.
Is it still used somewhere else in this repo?

**Comment by rfranzke** [comment]
You're right, I guess the occurrences of `packr` which I saw were due to an outdated local state of the extension.
/close
